version: '2.2'

services:

  turbo-geth:
    build: ./../..
    command: --nousb --metrics --metrics.expensive --pprof --pprof.addr=0.0.0.0 --pprof.port=6060 --private.api.addr=0.0.0.0:9999
    stop_grace_period: 2m
    volumes:
      - ${TG_DATADIR:-~/Library/TurboGeth}:/root/.turbogeth/
    ports:
      - 30303:30303
      - 8545:8545
      - 6060:6060
      - 9999:9999

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/etc/grafana/provisioning/dashboards

  restapi:
    build:
      context: ./../../
      dockerfile: ./cmd/restapi/Dockerfile
    command: --private.api.addr=turbo-geth:9999
    ports:
      - 8080:8080

  debugui:
    build: ./../../debug-web-ui
    stdin_open: true
    ports:
      - 3001:3000


