global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 5s

scrape_configs:
  - job_name: turbo-geth # example, how to connect prometheus to geth runned by docker-compose
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets:
          - turbo-geth:6060
          - turbo-geth:6061
          - turbo-geth:6062
          - host.docker.internal:6060 # this is how docker-for-mac allow to access host machine
          - host.docker.internal:6061
          - host.docker.internal:6062
          - 192.168.255.138:6060
          - 192.168.255.138:6061

  - job_name: turbo-geth2
    metrics_path: /debug/metrics/prometheus2
    scheme: http
    static_configs:
      - targets:
          - turbo-geth:6060
          - turbo-geth:6061
          - turbo-geth:6062
          - host.docker.internal:6060
          - host.docker.internal:6061
          - host.docker.internal:6062
          - 192.168.255.138:6060
          - 192.168.255.138:6061
