name = "Rinkeby"
data_dir = "rinkeby"

bootnodes = [
  "enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303",
  "enode://343149e4feefa15d882d9fe4ac7d88f885bd05ebb735e547f12e12080a9fa07c8014ca6fd7f373123488102fe5e34111f8509cf0b7de3f5b44339c9f25e87cb8@52.3.158.184:30303",
  "enode://b6b28890b006743680c52e64e0d16db57f28124885595fa03a562be1d2bf0f3a1da297d56b13da25fb992888fd556d4c1a27b1f39d531bde7de1921c90061cc6@159.89.28.211:30303",
]

[engine]
name = "clique"
[engine.params]
period = 15
epoch = 30000
[engine.params.genesis]
vanity = "0x52657370656374206d7920617574686f7269746168207e452e436172746d616e"
signers = [
    "0x42eb768f2244c8811c63729a21a3569731535f06",
    "0x7ffc57839b00206d1ad20c69a1981b489f772031",
    "0xb279182d99e65703f0076e4812653aab85fca0f0",
]

[hardforks]
eip140 = 1035301
eip145 = 3660663
eip150 = 2
eip155 = 2
eip160 = 0
eip161abc = 0
eip161d = 0
eip211 = 1035301
eip214 = 1035301
eip658 = 1035301
eip1014 = 3660663
eip1052 = 3660663
eip1283 = 3660663
eip1283_disable = 4321234
eip1283_reenable = 5435345
eip1344 = 5435345
eip1706 = 5435345
eip1884 = 5435345
eip2028 = 5435345

[params]
account_start_nonce = 0
chain_id = "0x4"
gas_limit_bound_divisor = 1024
max_code_size = 24576
maximum_extra_data_size = 65535
min_gas_limit = 5000
network_id = "0x4"

[genesis]
gas_limit = 4700000
timestamp = 1492009146

[precompiles.0.0x0000000000000000000000000000000000000001]
name = "ecrecover"
pricing = { formula = "linear", params = { base = 3000.0, word = 0 } }

[precompiles.0.0x0000000000000000000000000000000000000002]
name = "sha256"
pricing = { formula = "linear", params = { base = 60, word = 12 } }

[precompiles.0.0x0000000000000000000000000000000000000003]
name = "ripemd160"
pricing = { formula = "linear", params = { base = 600, word = 120 } }

[precompiles.0.0x0000000000000000000000000000000000000004]
name = "identity"
pricing = { formula = "linear", params = { base = 15, word = 3 } }

# EIP 1108 transition at block 5_435_345 (0x52efd1)
[precompiles.1035301.0x0000000000000000000000000000000000000005]
name = "modexp"
pricing = { formula = "modexp", params = { divisor = 20 } }

[precompiles.1035301.0x0000000000000000000000000000000000000006]
name = "alt_bn128_add"
pricing = { formula = "alt_bn128_const_operations", params = { price = 500 } }

[precompiles.1035301.0x0000000000000000000000000000000000000007]
name = "alt_bn128_mul"
pricing = { formula = "alt_bn128_const_operations", params = { price = 40000 } }

[precompiles.1035301.0x0000000000000000000000000000000000000008]
name = "alt_bn128_pairing"
pricing = { formula = "alt_bn128_pairing", params = { base = 100000, pair = 80000 } }

# EIP 1108 transition at block 5_435_345 (0x52efd1)
[precompiles.5435345.0x0000000000000000000000000000000000000006]
name = "alt_bn128_add"
pricing = { formula = "alt_bn128_const_operations", params = { price = 150 } }

[precompiles.5435345.0x0000000000000000000000000000000000000007]
name = "alt_bn128_mul"
pricing = { formula = "alt_bn128_const_operations", params = { price = 40000 } }

[precompiles.5435345.0x0000000000000000000000000000000000000008]
name = "alt_bn128_pairing"
pricing = { formula = "alt_bn128_pairing", params = { base = 45000, pair = 34000 } }

[precompiles.5435345.0x0000000000000000000000000000000000000009]
name = "blake2_f"
pricing = { formula = "blake2_f", params = { gas_per_round = 1 } }

[balances]
"0x0000000000000000000000000000000000000000" = "0x1"
"0x0000000000000000000000000000000000000001" = "0x1"
"0x0000000000000000000000000000000000000002" = "0x1"
"0x0000000000000000000000000000000000000003" = "0x1"
"0x0000000000000000000000000000000000000004" = "0x1"
"0x0000000000000000000000000000000000000005" = "0x1"
"0x0000000000000000000000000000000000000006" = "0x1"
"0x0000000000000000000000000000000000000007" = "0x1"
"0x0000000000000000000000000000000000000008" = "0x1"
"0x0000000000000000000000000000000000000009" = "0x1"
"0x000000000000000000000000000000000000000a" = "0x1"
"0x000000000000000000000000000000000000000b" = "0x1"
"0x000000000000000000000000000000000000000c" = "0x1"
"0x000000000000000000000000000000000000000d" = "0x1"
"0x000000000000000000000000000000000000000e" = "0x1"
"0x000000000000000000000000000000000000000f" = "0x1"
"0x0000000000000000000000000000000000000010" = "0x1"
"0x0000000000000000000000000000000000000011" = "0x1"
"0x0000000000000000000000000000000000000012" = "0x1"
"0x0000000000000000000000000000000000000013" = "0x1"
"0x0000000000000000000000000000000000000014" = "0x1"
"0x0000000000000000000000000000000000000015" = "0x1"
"0x0000000000000000000000000000000000000016" = "0x1"
"0x0000000000000000000000000000000000000017" = "0x1"
"0x0000000000000000000000000000000000000018" = "0x1"
"0x0000000000000000000000000000000000000019" = "0x1"
"0x000000000000000000000000000000000000001a" = "0x1"
"0x000000000000000000000000000000000000001b" = "0x1"
"0x000000000000000000000000000000000000001c" = "0x1"
"0x000000000000000000000000000000000000001d" = "0x1"
"0x000000000000000000000000000000000000001e" = "0x1"
"0x000000000000000000000000000000000000001f" = "0x1"
"0x0000000000000000000000000000000000000020" = "0x1"
"0x0000000000000000000000000000000000000021" = "0x1"
"0x0000000000000000000000000000000000000022" = "0x1"
"0x0000000000000000000000000000000000000023" = "0x1"
"0x0000000000000000000000000000000000000024" = "0x1"
"0x0000000000000000000000000000000000000025" = "0x1"
"0x0000000000000000000000000000000000000026" = "0x1"
"0x0000000000000000000000000000000000000027" = "0x1"
"0x0000000000000000000000000000000000000028" = "0x1"
"0x0000000000000000000000000000000000000029" = "0x1"
"0x000000000000000000000000000000000000002a" = "0x1"
"0x000000000000000000000000000000000000002b" = "0x1"
"0x000000000000000000000000000000000000002c" = "0x1"
"0x000000000000000000000000000000000000002d" = "0x1"
"0x000000000000000000000000000000000000002e" = "0x1"
"0x000000000000000000000000000000000000002f" = "0x1"
"0x0000000000000000000000000000000000000030" = "0x1"
"0x0000000000000000000000000000000000000031" = "0x1"
"0x0000000000000000000000000000000000000032" = "0x1"
"0x0000000000000000000000000000000000000033" = "0x1"
"0x0000000000000000000000000000000000000034" = "0x1"
"0x0000000000000000000000000000000000000035" = "0x1"
"0x0000000000000000000000000000000000000036" = "0x1"
"0x0000000000000000000000000000000000000037" = "0x1"
"0x0000000000000000000000000000000000000038" = "0x1"
"0x0000000000000000000000000000000000000039" = "0x1"
"0x000000000000000000000000000000000000003a" = "0x1"
"0x000000000000000000000000000000000000003b" = "0x1"
"0x000000000000000000000000000000000000003c" = "0x1"
"0x000000000000000000000000000000000000003d" = "0x1"
"0x000000000000000000000000000000000000003e" = "0x1"
"0x000000000000000000000000000000000000003f" = "0x1"
"0x0000000000000000000000000000000000000040" = "0x1"
"0x0000000000000000000000000000000000000041" = "0x1"
"0x0000000000000000000000000000000000000042" = "0x1"
"0x0000000000000000000000000000000000000043" = "0x1"
"0x0000000000000000000000000000000000000044" = "0x1"
"0x0000000000000000000000000000000000000045" = "0x1"
"0x0000000000000000000000000000000000000046" = "0x1"
"0x0000000000000000000000000000000000000047" = "0x1"
"0x0000000000000000000000000000000000000048" = "0x1"
"0x0000000000000000000000000000000000000049" = "0x1"
"0x000000000000000000000000000000000000004a" = "0x1"
"0x000000000000000000000000000000000000004b" = "0x1"
"0x000000000000000000000000000000000000004c" = "0x1"
"0x000000000000000000000000000000000000004d" = "0x1"
"0x000000000000000000000000000000000000004e" = "0x1"
"0x000000000000000000000000000000000000004f" = "0x1"
"0x0000000000000000000000000000000000000050" = "0x1"
"0x0000000000000000000000000000000000000051" = "0x1"
"0x0000000000000000000000000000000000000052" = "0x1"
"0x0000000000000000000000000000000000000053" = "0x1"
"0x0000000000000000000000000000000000000054" = "0x1"
"0x0000000000000000000000000000000000000055" = "0x1"
"0x0000000000000000000000000000000000000056" = "0x1"
"0x0000000000000000000000000000000000000057" = "0x1"
"0x0000000000000000000000000000000000000058" = "0x1"
"0x0000000000000000000000000000000000000059" = "0x1"
"0x000000000000000000000000000000000000005a" = "0x1"
"0x000000000000000000000000000000000000005b" = "0x1"
"0x000000000000000000000000000000000000005c" = "0x1"
"0x000000000000000000000000000000000000005d" = "0x1"
"0x000000000000000000000000000000000000005e" = "0x1"
"0x000000000000000000000000000000000000005f" = "0x1"
"0x0000000000000000000000000000000000000060" = "0x1"
"0x0000000000000000000000000000000000000061" = "0x1"
"0x0000000000000000000000000000000000000062" = "0x1"
"0x0000000000000000000000000000000000000063" = "0x1"
"0x0000000000000000000000000000000000000064" = "0x1"
"0x0000000000000000000000000000000000000065" = "0x1"
"0x0000000000000000000000000000000000000066" = "0x1"
"0x0000000000000000000000000000000000000067" = "0x1"
"0x0000000000000000000000000000000000000068" = "0x1"
"0x0000000000000000000000000000000000000069" = "0x1"
"0x000000000000000000000000000000000000006a" = "0x1"
"0x000000000000000000000000000000000000006b" = "0x1"
"0x000000000000000000000000000000000000006c" = "0x1"
"0x000000000000000000000000000000000000006d" = "0x1"
"0x000000000000000000000000000000000000006e" = "0x1"
"0x000000000000000000000000000000000000006f" = "0x1"
"0x0000000000000000000000000000000000000070" = "0x1"
"0x0000000000000000000000000000000000000071" = "0x1"
"0x0000000000000000000000000000000000000072" = "0x1"
"0x0000000000000000000000000000000000000073" = "0x1"
"0x0000000000000000000000000000000000000074" = "0x1"
"0x0000000000000000000000000000000000000075" = "0x1"
"0x0000000000000000000000000000000000000076" = "0x1"
"0x0000000000000000000000000000000000000077" = "0x1"
"0x0000000000000000000000000000000000000078" = "0x1"
"0x0000000000000000000000000000000000000079" = "0x1"
"0x000000000000000000000000000000000000007a" = "0x1"
"0x000000000000000000000000000000000000007b" = "0x1"
"0x000000000000000000000000000000000000007c" = "0x1"
"0x000000000000000000000000000000000000007d" = "0x1"
"0x000000000000000000000000000000000000007e" = "0x1"
"0x000000000000000000000000000000000000007f" = "0x1"
"0x0000000000000000000000000000000000000080" = "0x1"
"0x0000000000000000000000000000000000000081" = "0x1"
"0x0000000000000000000000000000000000000082" = "0x1"
"0x0000000000000000000000000000000000000083" = "0x1"
"0x0000000000000000000000000000000000000084" = "0x1"
"0x0000000000000000000000000000000000000085" = "0x1"
"0x0000000000000000000000000000000000000086" = "0x1"
"0x0000000000000000000000000000000000000087" = "0x1"
"0x0000000000000000000000000000000000000088" = "0x1"
"0x0000000000000000000000000000000000000089" = "0x1"
"0x000000000000000000000000000000000000008a" = "0x1"
"0x000000000000000000000000000000000000008b" = "0x1"
"0x000000000000000000000000000000000000008c" = "0x1"
"0x000000000000000000000000000000000000008d" = "0x1"
"0x000000000000000000000000000000000000008e" = "0x1"
"0x000000000000000000000000000000000000008f" = "0x1"
"0x0000000000000000000000000000000000000090" = "0x1"
"0x0000000000000000000000000000000000000091" = "0x1"
"0x0000000000000000000000000000000000000092" = "0x1"
"0x0000000000000000000000000000000000000093" = "0x1"
"0x0000000000000000000000000000000000000094" = "0x1"
"0x0000000000000000000000000000000000000095" = "0x1"
"0x0000000000000000000000000000000000000096" = "0x1"
"0x0000000000000000000000000000000000000097" = "0x1"
"0x0000000000000000000000000000000000000098" = "0x1"
"0x0000000000000000000000000000000000000099" = "0x1"
"0x000000000000000000000000000000000000009a" = "0x1"
"0x000000000000000000000000000000000000009b" = "0x1"
"0x000000000000000000000000000000000000009c" = "0x1"
"0x000000000000000000000000000000000000009d" = "0x1"
"0x000000000000000000000000000000000000009e" = "0x1"
"0x000000000000000000000000000000000000009f" = "0x1"
"0x00000000000000000000000000000000000000a0" = "0x1"
"0x00000000000000000000000000000000000000a1" = "0x1"
"0x00000000000000000000000000000000000000a2" = "0x1"
"0x00000000000000000000000000000000000000a3" = "0x1"
"0x00000000000000000000000000000000000000a4" = "0x1"
"0x00000000000000000000000000000000000000a5" = "0x1"
"0x00000000000000000000000000000000000000a6" = "0x1"
"0x00000000000000000000000000000000000000a7" = "0x1"
"0x00000000000000000000000000000000000000a8" = "0x1"
"0x00000000000000000000000000000000000000a9" = "0x1"
"0x00000000000000000000000000000000000000aa" = "0x1"
"0x00000000000000000000000000000000000000ab" = "0x1"
"0x00000000000000000000000000000000000000ac" = "0x1"
"0x00000000000000000000000000000000000000ad" = "0x1"
"0x00000000000000000000000000000000000000ae" = "0x1"
"0x00000000000000000000000000000000000000af" = "0x1"
"0x00000000000000000000000000000000000000b0" = "0x1"
"0x00000000000000000000000000000000000000b1" = "0x1"
"0x00000000000000000000000000000000000000b2" = "0x1"
"0x00000000000000000000000000000000000000b3" = "0x1"
"0x00000000000000000000000000000000000000b4" = "0x1"
"0x00000000000000000000000000000000000000b5" = "0x1"
"0x00000000000000000000000000000000000000b6" = "0x1"
"0x00000000000000000000000000000000000000b7" = "0x1"
"0x00000000000000000000000000000000000000b8" = "0x1"
"0x00000000000000000000000000000000000000b9" = "0x1"
"0x00000000000000000000000000000000000000ba" = "0x1"
"0x00000000000000000000000000000000000000bb" = "0x1"
"0x00000000000000000000000000000000000000bc" = "0x1"
"0x00000000000000000000000000000000000000bd" = "0x1"
"0x00000000000000000000000000000000000000be" = "0x1"
"0x00000000000000000000000000000000000000bf" = "0x1"
"0x00000000000000000000000000000000000000c0" = "0x1"
"0x00000000000000000000000000000000000000c1" = "0x1"
"0x00000000000000000000000000000000000000c2" = "0x1"
"0x00000000000000000000000000000000000000c3" = "0x1"
"0x00000000000000000000000000000000000000c4" = "0x1"
"0x00000000000000000000000000000000000000c5" = "0x1"
"0x00000000000000000000000000000000000000c6" = "0x1"
"0x00000000000000000000000000000000000000c7" = "0x1"
"0x00000000000000000000000000000000000000c8" = "0x1"
"0x00000000000000000000000000000000000000c9" = "0x1"
"0x00000000000000000000000000000000000000ca" = "0x1"
"0x00000000000000000000000000000000000000cb" = "0x1"
"0x00000000000000000000000000000000000000cc" = "0x1"
"0x00000000000000000000000000000000000000cd" = "0x1"
"0x00000000000000000000000000000000000000ce" = "0x1"
"0x00000000000000000000000000000000000000cf" = "0x1"
"0x00000000000000000000000000000000000000d0" = "0x1"
"0x00000000000000000000000000000000000000d1" = "0x1"
"0x00000000000000000000000000000000000000d2" = "0x1"
"0x00000000000000000000000000000000000000d3" = "0x1"
"0x00000000000000000000000000000000000000d4" = "0x1"
"0x00000000000000000000000000000000000000d5" = "0x1"
"0x00000000000000000000000000000000000000d6" = "0x1"
"0x00000000000000000000000000000000000000d7" = "0x1"
"0x00000000000000000000000000000000000000d8" = "0x1"
"0x00000000000000000000000000000000000000d9" = "0x1"
"0x00000000000000000000000000000000000000da" = "0x1"
"0x00000000000000000000000000000000000000db" = "0x1"
"0x00000000000000000000000000000000000000dc" = "0x1"
"0x00000000000000000000000000000000000000dd" = "0x1"
"0x00000000000000000000000000000000000000de" = "0x1"
"0x00000000000000000000000000000000000000df" = "0x1"
"0x00000000000000000000000000000000000000e0" = "0x1"
"0x00000000000000000000000000000000000000e1" = "0x1"
"0x00000000000000000000000000000000000000e2" = "0x1"
"0x00000000000000000000000000000000000000e3" = "0x1"
"0x00000000000000000000000000000000000000e4" = "0x1"
"0x00000000000000000000000000000000000000e5" = "0x1"
"0x00000000000000000000000000000000000000e6" = "0x1"
"0x00000000000000000000000000000000000000e7" = "0x1"
"0x00000000000000000000000000000000000000e8" = "0x1"
"0x00000000000000000000000000000000000000e9" = "0x1"
"0x00000000000000000000000000000000000000ea" = "0x1"
"0x00000000000000000000000000000000000000eb" = "0x1"
"0x00000000000000000000000000000000000000ec" = "0x1"
"0x00000000000000000000000000000000000000ed" = "0x1"
"0x00000000000000000000000000000000000000ee" = "0x1"
"0x00000000000000000000000000000000000000ef" = "0x1"
"0x00000000000000000000000000000000000000f0" = "0x1"
"0x00000000000000000000000000000000000000f1" = "0x1"
"0x00000000000000000000000000000000000000f2" = "0x1"
"0x00000000000000000000000000000000000000f3" = "0x1"
"0x00000000000000000000000000000000000000f4" = "0x1"
"0x00000000000000000000000000000000000000f5" = "0x1"
"0x00000000000000000000000000000000000000f6" = "0x1"
"0x00000000000000000000000000000000000000f7" = "0x1"
"0x00000000000000000000000000000000000000f8" = "0x1"
"0x00000000000000000000000000000000000000f9" = "0x1"
"0x00000000000000000000000000000000000000fa" = "0x1"
"0x00000000000000000000000000000000000000fb" = "0x1"
"0x00000000000000000000000000000000000000fc" = "0x1"
"0x00000000000000000000000000000000000000fd" = "0x1"
"0x00000000000000000000000000000000000000fe" = "0x1"
"0x00000000000000000000000000000000000000ff" = "0x1"
"0x31b98d14007bdee637298086988a0bbd31184523" = "0x200000000000000000000000000000000000000000000000000000000000000"