name: Lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'release/**'
      - performance
      - performance-stable

defaults:
  run:
    shell: bash

jobs:
  lint:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ format('{0}-{1}', github.workflow, github.ref) }}
      cancel-in-progress: true

    steps:
      - name: Checkout custom actions
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: ./.github/actions/setup-erigon
        id: erigon
        with:
          modcache: false

      - name: Restore Go module cache
        id: restore-modcache
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.erigon.outputs.modcache }}/cache/download
          # We can never know ahead of time what to match against
          key: gomodcache-lint-${{ runner.os }}-${{ hashFiles('go.sum') }}-alwaysmiss
          # We can use a regular build to bootstrap here, we only add some extra metadata
          restore-keys: |
            gomodcache-lint-${{ runner.os }}-${{ hashFiles('go.sum') }}-
            gomodcache-${{ runner.os }}-${{ hashFiles('go.sum') }}-

      - uses: ./.github/actions/restore-build-cache
        id: restore-build

      - name: Restore golangci-lint cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/golangci-lint
          key: golangci-lint-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: golangci-lint-${{ runner.os }}-

      - run: make lintci

      - uses: ./.github/actions/save-build-cache
        if: always() && steps.restore-build.outcome == 'success'

      - uses: ./.github/actions/save-mod-cache
        if: always() && steps.restore-modcache.outcome == 'success'
        with:
          modcache: ${{ steps.erigon.outputs.modcache }}
          prefix: modcache-lint

      - name: Save golangci-lint cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/golangci-lint
          key: golangci-lint-${{ runner.os }}-${{ hashFiles('go.mod') }}
