name: Manifest Check
on:
  push:
    branches:
      - devel
      - e35
      - 'release/**'
    paths:
      - 'go.mod'
  pull_request:
    branches:
      - devel
      - e35
      - 'release/**'
    paths:
      - 'go.mod'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-snap-modifications:
    runs-on: ubuntu-22.04
    outputs:
      modified: ${{ steps.check-modified.outputs.modified }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Ensures we fetch enough history to compare

      - name: Is ledgerwatch/erigon-snapshots updated in go.mod
        id: check-modified
        run: |
          DIFF=$(git diff HEAD~1 HEAD -- go.mod | grep 'github.com/ledgerwatch/erigon-snapshot')
          if [[ ! -z "$DIFF" ]]; then
            echo "::set-output name=modified::true"
          else
            echo "::set-output name=modified::false"
          fi

  ManifestCheck:
    needs: check-snap-modifications
    if: needs.check-modified.outputs.modified == 'true' && (${{ github.event_name == 'push' || !github.event.pull_request.draft }})
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install build-essential

      - name: Build
        run: make downloader

      - name: mainnet webseeds
        run: |
          ./build/bin/downloader manifest-verify --chain mainnet

      - name: bor-mainnet webseeds
        run: |
          ./build/bin/downloader manifest-verify --chain bor-mainnet

      - name: gnosis webseeds
        run: |
          ./build/bin/downloader manifest-verify --chain gnosis

      - name: mumbai webseeds
        run: |
          ./build/bin/downloader manifest-verify --chain mumbai

      - name: sepolia webseeds
        run: |
          ./build/bin/downloader manifest-verify --chain sepolia

      - name: chiado webseeds
        run: |
          ./build/bin/downloader manifest-verify --chain chiado

      - name: amoy webseeds
        run: |
          ./build/bin/downloader manifest-verify --chain amoy
