name: Manifest Check
on:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - 'go.mod'
  pull_request:
    branches:
      - main
      - 'release/**'
    paths:
      - 'go.mod'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  ManifestCheck:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: make downloader
      - run: echo $ModModified
      - run: ./build/bin/downloader manifest-verify --chain mainnet     --webseed 'https://erigon3-v1-snapshots-mainnet.erigon.network'
      - run: ./build/bin/downloader manifest-verify --chain bor-mainnet --webseed 'https://erigon3-v1-snapshots-bor-mainnet.erigon.network'
      - run: ./build/bin/downloader manifest-verify --chain gnosis      --webseed 'https://erigon3-v1-snapshots-gnosis.erigon.network'
      - run: ./build/bin/downloader manifest-verify --chain chiado      --webseed 'https://erigon3-v1-snapshots-chiado.erigon.network'
      - run: ./build/bin/downloader manifest-verify --chain sepolia     --webseed 'https://erigon3-v1-snapshots-sepolia.erigon.network'
      - run: ./build/bin/downloader manifest-verify --chain amoy        --webseed 'https://erigon3-v1-snapshots-amoy.erigon.network'
