name: Nightly - Compare Blocks

on:
  schedule:
    - cron: '30 3 * * *'  # run at 3:30am to give time for other suites to run first
  workflow_dispatch:

jobs:
  compare-blocks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodes:
          - name: "Integration 5"
            erigon: "http://34.175.214.161:8500"
            zkevm: "http://34.175.214.161:8505"
            sequencer: "http://34.175.214.161:8005"
            compare-blocks: 1000
            allowed-block-diff: 2000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get github.com/google/go-cmp/cmp

      - name: Build the compare_blocks binary
        run: go build -o compare_blocks zk/debug_tools/nightly-block-compare/main.go

      - name: Run block comparison
        run: |
          echo "Comparing blocks for pair: ${{ matrix.nodes.name }}"
          ./compare_blocks -erigon ${{ matrix.nodes.erigon }} -zkevm ${{ matrix.nodes.zkevm }} -sequencer ${{ matrix.nodes.sequencer }} -blocks ${{matrix.nodes.compare-blocks}} -diff ${{ matrix.nodes.allowed-block-diff }}
